# Generated by Django 3.1 on 2024-08-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='DeporteD',
            fields=[
                ('idDeporte', models.AutoField(db_column='idDeporte', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('horario', models.DateField(verbose_name='horario')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.categoria', verbose_name='idCategoria')),
            ],
        ),
    ]
