# Generated by Django 3.1 on 2024-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deported',
            name='horario',
            field=models.FloatField(verbose_name='horario'),
        ),
    ]
