# Generated by Django 3.1 on 2024-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuota', '0002_auto_20240827_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fechap',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
    ]
