# Generated by Django 3.1 on 2024-08-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre y Apellido')),
                ('fechan', models.DateField(verbose_name='Fecha Nacimiento')),
                ('dire', models.CharField(max_length=50, verbose_name='Direccion')),
                ('cp', models.CharField(max_length=6, verbose_name='codigo postal')),
                ('tel', models.CharField(max_length=15, verbose_name='telefono')),
            ],
        ),
    ]
