# Generated by Django 3.1 on 2024-08-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(db_column='Código del Servicio', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('costo', models.FloatField(max_length=50, verbose_name='Costo del Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('idContratacion', models.AutoField(db_column='idContratacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('nomContratante', models.TextField(max_length=25, verbose_name='nomContratante')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio', verbose_name='idServicio')),
            ],
        ),
    ]
