# Generated by Django 3.1 on 2024-08-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20240826_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='fecha',
            field=models.DateField(verbose_name='fecha'),
        ),
    ]
